import { ReactChildren } from '@/types'
import Head from 'next/head'
import React from 'react'

const AppLayout = ({ children }: ReactChildren) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <header>HEADER</header>
        <main>{children}</main>
        <footer>FOOTER</footer>
      </div>
    </>
  )
}

export default AppLayout
