import { ReactChildren } from '@/types'
import Head from 'next/head'
import React from 'react'
import AppHeader from '../AppHeader'

interface Props extends ReactChildren {
  headTitle: string
}

const AppLayout = ({ children, headTitle }: Props) => {
  return (
    <>
      <Head>
        <title>{headTitle}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='relative flex font-bold text-primary flex-col min-h-screen max-w-screen bg-dotted-spacing-10 bg-background bg-dotted-black bg-fixed'>
        <AppHeader />
        <main className='flex-1 p-2 m-auto flex flex-col gap-4 max-w-7xl w-full'>
          {children}
        </main>
        <footer>FOOTER</footer>
      </div>
    </>
  )
}

export default AppLayout
